name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags-ignore:
      - '*'
  workflow_dispatch:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --build-arg goVersion=1.18.4 \
            --build-arg kubeVersion=1.24.3 \
            --build-arg ttydVersion=1.6.3 \
            -t ghcr.io/${{ github.repository_owner }}/go-docker-dev:1.18.4 \
            -f Dockerfile \
            .
